FROM node

RUN mkdir /gitbook
COPY ./* /gitbook/
WORKDIR /gitbook

RUN pwd && ls

RUN npm install -g gitbook-cli

RUN npm install
RUN gitbook build
RUN rm -rf node_modules

RUN ls ./_book

CMD cp -R /gitbook/_book/. /book && pwd && ls